# Generated by Django 4.1.1 on 2022-09-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'AutomobilioModelis',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8)),
                ('vin', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=30)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobiliomodelis')),
            ],
            options={
                'verbose_name_plural': 'Automobilis',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Paslauga',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('s', 'Sukurtas'), ('p', 'Priimtas'), ('v', 'Vykdomas'), ('i', 'Ivykdytas')], default='s', max_length=1)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automobilis')),
            ],
            options={
                'verbose_name_plural': 'Uzsakymas',
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.uzsakymas')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.paslauga')),
            ],
            options={
                'verbose_name_plural': 'Uzsakymo eilutes',
            },
        ),
    ]
