# Generated by Django 4.1.1 on 2022-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_automobiliomodelis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='amount',
            field=models.FloatField(verbose_name='Viso'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='order_date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
