# Generated by Django 4.1.1 on 2022-09-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_alter_uzsakymas_amount_alter_uzsakymas_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='autoservisas.automobilis'),
        ),
    ]
