# Generated by Django 4.1.1 on 2022-09-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_alter_uzsakymas_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoeilutes',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='autoservisas.uzsakymas'),
        ),
    ]
