# Generated by Django 4.1.1 on 2022-09-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_alter_uzsakymoeilutes_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paslauga',
            name='price',
        ),
    ]
