# Generated by Django 4.1.1 on 2022-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_remove_paslauga_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymoeilutes',
            name='price',
        ),
        migrations.AddField(
            model_name='paslauga',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
