# Generated by Django 4.1.1 on 2022-09-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_remove_uzsakymoeilutes_price_paslauga_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymoeilutes',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymoeilutes', to='autoservisas.uzsakymas'),
        ),
    ]
