# Generated by Django 4.1.1 on 2022-09-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0011_alter_uzsakymoeilutes_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='vehicle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto', to='autoservisas.automobiliomodelis'),
        ),
    ]
